### ISSUE TITLE
Add CI for rz-tracetest

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-tracetest#13]

**Comment by Rot127** [comment]
What specifically do you think about? Only building it for the beginning? Or is testing traces also a must?

**Comment by wargio** [comment]
probably just building it

**Comment by XVilka** [comment]
At the first stage just building will be fine. We could create basic tests though - just checking if it converts some mock binaries consisting of 2-3 instructions for each architecture. This way we will check most code paths.
